packages:
  - 'packages/*'

catalog:
  # TypeScript
  typescript: ^5.9.3
  '@types/node': ^22.10.2

  # Testing
  vitest: ^3.0.5
  '@vitest/ui': ^3.0.5

  # Build tools
  tsup: ^8.3.5
  tsx: ^4.19.2

  # Linting
  eslint: ^9.17.0
  '@typescript-eslint/eslint-plugin': ^8.18.2
  '@typescript-eslint/parser': ^8.18.2
